#!/usr/bin/env bash

# ============================================================
# run_make_framework_assets_v2.sh
#
# Purpose:
#   One-click generation of all small visual assets used in the
#   revised SBP-PG framework figure.
#
# Correct framework logic:
#
#   Branch 1: Synthetic training data generation
#       training mask
#           -> SBP-PG generated dermoscopy image
#           -> synthetic image-mask pair
#           -> augmented segmentation training set
#
#   Branch 2: Real test-set segmentation evaluation
#       real test image
#           -> downstream segmentation model
#           -> predicted mask / overlay / metrics
#
# Important:
#   The synthetic generated image branch and the real test-set evaluation
#   branch are different branches.
#
#   Do NOT force generated_train_image and pred_test_mask to come from
#   the same sample.
#
#   Required correspondence:
#       TRAIN_MASK_PATH and GENERATED_TRAIN_IMAGE_PATH
#       should correspond to the same training sample.
#
#       TEST_IMAGE_PATH, TEST_GT_MASK_PATH, and PRED_TEST_MASK_PATH
#       should correspond to the same real test sample.
#
# ============================================================


# ============================================================
# 1. Safety settings
# ============================================================

set -euo pipefail


# ============================================================
# 2. Project directory
# ============================================================

PROJECT_DIR="/data/zjy_work/BGDiff"


# ============================================================
# 3. Python script path
# ============================================================
# Your current Python file is stored at:
#   /data/zjy_work/BGDiff/Ours/make_framework_assets_v2.py
# ============================================================

PY_SCRIPT="${PROJECT_DIR}/Ours/make_framework_assets_v2.py"


# ============================================================
# 4. Output directory
# ============================================================
# All generated framework assets will be saved here.
# You can later use these images in PowerPoint, Illustrator, Inkscape,
# or directly replace small thumbnails in Image2-generated figures.
# ============================================================

OUT_DIR="${PROJECT_DIR}/Ours/paper_assets/framework_assets_v2"

mkdir -p "${OUT_DIR}"


# ============================================================
# 5. Synthetic training data generation branch
# ============================================================
# These two files should correspond to the SAME training sample.
#
# TRAIN_MASK_PATH:
#   The lesion mask from the ISIC training set.
#
# GENERATED_TRAIN_IMAGE_PATH:
#   The dermoscopy image generated by SBP-PG from this training mask.
#
# You need to replace the example paths below with your real paths.
# ============================================================

TRAIN_MASK_PATH="/data/zjy_work/BGDiff/asset/Train_real_1.png"

GENERATED_TRAIN_IMAGE_PATH="/data/zjy_work/BGDiff/asset/Train_gen_1.png"


# ============================================================
# 6. Real test-set segmentation evaluation branch
# ============================================================
# These three files should correspond to the SAME real test sample.
#
# TEST_IMAGE_PATH:
#   Real dermoscopy image from the ISIC test set.
#
# TEST_GT_MASK_PATH:
#   Ground-truth lesion mask of the real test image.
#   This is used for overlay visualization.
#
# PRED_TEST_MASK_PATH:
#   Prediction mask produced by BGDNet or another fixed downstream
#   segmentation model on TEST_IMAGE_PATH.
#
# Important:
#   PRED_TEST_MASK_PATH should be the prediction of TEST_IMAGE_PATH,
#   not the prediction of GENERATED_TRAIN_IMAGE_PATH.
# ============================================================

TEST_IMAGE_PATH="/data/zjy_work/BGDiff/asset/test_ISIC_0014997.jpg"

TEST_GT_MASK_PATH="/data/zjy_work/BGDiff/asset/real_ISIC_0014997.jpg"

PRED_TEST_MASK_PATH="/data/zjy_work/BGDiff/asset/pre_ISIC_0014997.jpg"


# ============================================================
# 7. Output asset size
# ============================================================
# Recommended:
#   512  : enough for most framework thumbnails
#   768  : better for high-resolution figure editing
#   1024 : useful if you need enlarged local details
# ============================================================

ASSET_SIZE=512


# ============================================================
# 8. Test-set metrics for the small metrics bar
# ============================================================
# Replace these with your real test-set results.
#
# These values are only used to generate:
#   F_metrics_bar.png
#
# In the paper, the formal quantitative results should still be reported
# in a separate table.
# ============================================================

DICE=0.91
IOU=0.84
SENSITIVITY=0.90
SPECIFICITY=0.97


# ============================================================
# 9. Optional conda environment
# ============================================================
# Uncomment this part if you need to activate your Python environment.
#
# Required packages:
#   numpy
#   opencv-python
#   pillow
#   matplotlib
# ============================================================

# source ~/miniconda3/etc/profile.d/conda.sh
# conda activate bgdiff


# ============================================================
# 10. Check required files
# ============================================================

echo "[INFO] Checking input files..."

if [ ! -f "${PY_SCRIPT}" ]; then
  echo "[ERROR] Python script not found:"
  echo "        ${PY_SCRIPT}"
  exit 1
fi

if [ ! -f "${TRAIN_MASK_PATH}" ]; then
  echo "[ERROR] Training mask not found:"
  echo "        ${TRAIN_MASK_PATH}"
  exit 1
fi

if [ ! -f "${GENERATED_TRAIN_IMAGE_PATH}" ]; then
  echo "[ERROR] Generated training image not found:"
  echo "        ${GENERATED_TRAIN_IMAGE_PATH}"
  exit 1
fi

if [ ! -f "${TEST_IMAGE_PATH}" ]; then
  echo "[ERROR] Real test image not found:"
  echo "        ${TEST_IMAGE_PATH}"
  exit 1
fi

if [ ! -f "${TEST_GT_MASK_PATH}" ]; then
  echo "[WARN] Test ground-truth mask not found:"
  echo "       ${TEST_GT_MASK_PATH}"
  echo "       Overlay will not include GT contour if unavailable."
fi

if [ ! -f "${PRED_TEST_MASK_PATH}" ]; then
  echo "[WARN] Test prediction mask not found:"
  echo "       ${PRED_TEST_MASK_PATH}"
  echo "       If supported by Python code, a placeholder may be used."
fi


# ============================================================
# 11. Export variables to the Python block
# ============================================================

export PY_SCRIPT
export TRAIN_MASK_PATH
export GENERATED_TRAIN_IMAGE_PATH
export TEST_IMAGE_PATH
export TEST_GT_MASK_PATH
export PRED_TEST_MASK_PATH
export OUT_DIR
export ASSET_SIZE
export DICE
export IOU
export SENSITIVITY
export SPECIFICITY


# ============================================================
# 12. Run Python asset generation
# ============================================================
# This heredoc imports generate_framework_assets_v2 from:
#
#   /data/zjy_work/BGDiff/Ours/make_framework_assets_v2.py
#
# Therefore, you do not need to modify the __main__ part of the Python file.
# You only need to edit the paths in this shell script.
# ============================================================

echo "[INFO] Generating framework assets..."
echo "[INFO] Python script: ${PY_SCRIPT}"
echo "[INFO] Output directory: ${OUT_DIR}"

python - <<'PY'
import os
import sys

py_script = os.environ["PY_SCRIPT"]
script_dir = os.path.dirname(os.path.abspath(py_script))

# Allow importing make_framework_assets_v2.py from its folder.
sys.path.insert(0, script_dir)

from make_framework_assets_v2 import generate_framework_assets_v2


def none_if_missing_or_empty(path):
    """
    Convert an optional path to None if it does not exist.
    """
    if path is None:
        return None
    path = path.strip()
    if path == "":
        return None
    if not os.path.isfile(path):
        return None
    return path


train_mask_path = os.environ["TRAIN_MASK_PATH"]
generated_train_image_path = os.environ["GENERATED_TRAIN_IMAGE_PATH"]
test_image_path = os.environ["TEST_IMAGE_PATH"]

test_gt_mask_path = none_if_missing_or_empty(
    os.environ.get("TEST_GT_MASK_PATH", "")
)

pred_test_mask_path = none_if_missing_or_empty(
    os.environ.get("PRED_TEST_MASK_PATH", "")
)

out_dir = os.environ["OUT_DIR"]
asset_size = int(os.environ.get("ASSET_SIZE", "512"))

metrics = {
    "Dice": float(os.environ.get("DICE", "0.91")),
    "IoU": float(os.environ.get("IOU", "0.84")),
    "Sen.": float(os.environ.get("SENSITIVITY", "0.90")),
    "Spe.": float(os.environ.get("SPECIFICITY", "0.97")),
}

generate_framework_assets_v2(
    train_mask_path=train_mask_path,
    generated_train_image_path=generated_train_image_path,
    test_image_path=test_image_path,
    test_gt_mask_path=test_gt_mask_path,
    pred_test_mask_path=pred_test_mask_path,
    out_dir=out_dir,
    size=asset_size,
    metrics=metrics,
)

print("[OK] Asset generation finished.")
print(f"[OK] Saved to: {out_dir}")
PY


# ============================================================
# 13. List generated files
# ============================================================

echo "[INFO] Generated files:"
ls -lh "${OUT_DIR}"

echo "[DONE] Framework asset generation completed successfully."
